<?php

class m150326_081048_update_property_info_details_table extends CDbMigration
{

    // Use safeUp/safeDown to do migration with transaction
    public function safeUp()
    {
        $this->getDbConnection()->createCommand("
ALTER TABLE  `property_info_details` 
    ADD  `lot_sqft` INT( 11 ) NULL DEFAULT NULL ,
    ADD  `lot_depth` INT( 11 ) NULL DEFAULT NULL ,
    ADD  `lot_frontage` INT( 11 ) NULL DEFAULT NULL ,

    ADD  `subdivision_name_xp` VARCHAR( 30 ) NULL DEFAULT NULL ,
    ADD  `city` VARCHAR( 32 ) NULL DEFAULT NULL ,
    ADD  `town` VARCHAR( 32 ) NULL DEFAULT NULL ,
    ADD  `county` VARCHAR( 20 ) NULL DEFAULT NULL ,
    ADD  `subdivision_number` TINYINT( 4 ) NULL DEFAULT NULL ,
    ADD  `subdivision_num_search` TINYINT( 4 ) NULL DEFAULT NULL ,
    ADD  `metro_map_coor` VARCHAR( 2 ) NULL DEFAULT NULL ,
    ADD  `metro_map_page` TINYINT( 2 ) NULL DEFAULT NULL ,
    ADD  `metro_map_coor_xp` VARCHAR( 2 ) NULL DEFAULT NULL ,
    ADD  `metro_map_page_xp` TINYINT( 3 ) NULL DEFAULT NULL ,

    ADD  `add_liv_area` INT( 11 ) NULL DEFAULT NULL ,
    ADD  `total_liv_area` INT( 11 ) NULL DEFAULT NULL ,
    ADD  `mh_year_built` TINYINT( 4 ) NULL DEFAULT NULL ,
    ADD  `beds_total_poss` TINYINT( 2 ) NULL DEFAULT NULL ,
    ADD  `pool_indoor` enum('No', 'Yes') DEFAULT 'No' ,
    ADD  `spa_indoor`  enum('No', 'Yes') DEFAULT 'No' ,


    ADD  `model` VARCHAR( 10 ) NULL DEFAULT NULL ,
    ADD  `built_desc` VARCHAR( 18 ) NULL DEFAULT NULL ,
    ADD  `prop_desc` VARCHAR( 128 ) NULL DEFAULT NULL ,
    ADD  `parking_spaces` VARCHAR( 15 ) NULL DEFAULT NULL ,
    ADD  `carport_type` enum('', 'Attached Carport', 'Detached Carport') DEFAULT '' ,
    ADD  `converted_garage` enum('No', 'Yes') DEFAULT 'No' ,
    ADD  `studio` enum('No', 'Yes') DEFAULT 'No' ,
    ADD  `condo_conversion` enum('No', 'Yes') DEFAULT 'No' ,
    ADD  `unit_desc` VARCHAR( 128 ) NULL DEFAULT NULL ,


    ADD  `compass_point` enum('', 'South', 'North', 'West', 'East') DEFAULT '' ,
    ADD  `house_faces` enum('', 'South', 'North', 'West', 'East', 'M', 'G') DEFAULT '' ,
    ADD  `house_views` VARCHAR( 100 ) NULL DEFAULT NULL ,

    ADD  `jr_high_school` VARCHAR( 32 ) NULL DEFAULT NULL ,
    ADD  `high_school` VARCHAR( 36 ) NULL DEFAULT NULL ,
    ADD  `elementary_school` VARCHAR( 32 ) NULL DEFAULT NULL ,

    ADD  `association_features_available` VARCHAR( 320 ) NULL DEFAULT NULL ,
    ADD  `association_fee_1` INT( 11 ) NULL DEFAULT NULL ,
    ADD  `association_fee_1_type` enum('', 'Monthly', 'Quarterly', 'Yearly', 'None') DEFAULT '' ,
    ADD  `association_name` VARCHAR( 20 ) NULL DEFAULT NULL ,
    ADD  `association_fee_includes` VARCHAR( 132 ) NULL DEFAULT NULL ,
    ADD  `assessment` enum('No', 'Yes') DEFAULT 'No' ,
    ADD  `assessment_amount` INT( 11 ) NULL DEFAULT NULL ,
    ADD  `assessment_amount_type` enum('', 'Quarterly', 'Annually', 'Monthly') DEFAULT '' ,
    ADD  `sidlid` enum('No', 'Yes') DEFAULT 'No' ,
    ADD  `sidlid_annual_amount` INT( 11 ) NULL DEFAULT NULL ,
    ADD  `sidlid_balance` INT( 11 ) NULL DEFAULT NULL ,
    ADD  `association_fee_2` INT( 11 ) NULL DEFAULT NULL ,
    ADD  `association_fee_2_type` enum('', 'Monthly', 'Quarterly', 'Yearly', 'None') DEFAULT '' ,
    ADD  `master_plan_fee_amount`  INT( 11 ) NULL DEFAULT NULL ,
    ADD  `master_plan_fee_type` enum('', 'Monthly', 'Quarterly', 'Yearly', 'None') DEFAULT '' ,
    ADD  `security` VARCHAR( 60 ) NULL DEFAULT NULL ,
    ADD  `hoa_minimum_rental_cycle` enum('', '6 Months', '3 Months', 'Monthly', 'Annual', 'Other') DEFAULT '' ,
    ADD  `age_restricted_community` enum('No', 'Yes') DEFAULT 'No' ,
    ADD  `services_available_on_site` VARCHAR( 128 ) NULL DEFAULT NULL ,
    ADD  `on_site_staff` enum('No', 'Yes') DEFAULT 'No' ,
    ADD  `on_site_staff_includes` VARCHAR( 128 ) NULL DEFAULT NULL ,
    ADD  `association_phone` VARCHAR( 12 ) NULL DEFAULT NULL ,
    ADD  `restrictions` VARCHAR( 22 ) NULL DEFAULT NULL ,
    ADD  `prop_amenities_description` VARCHAR( 128 ) NULL DEFAULT NULL ,
    ADD  `maintenance` INT( 11 ) NULL DEFAULT NULL ,
    ADD  `management` INT( 11 ) NULL DEFAULT NULL, -- 

    ADD  `num_terraces` TINYINT( 2 ) NULL DEFAULT NULL ,
    ADD  `terrace_total_sqft` TINYINT( 5 ) NULL DEFAULT NULL ,
    ADD  `terrace_location` VARCHAR( 50 ) NULL DEFAULT NULL ,
    ADD  `storage_unit_desc` enum('', 'Association Owned', 'Leased', 'Owned') DEFAULT '' ,
    ADD  `storage_units_num` TINYINT( 2 ) NULL DEFAULT NULL ,
    ADD  `storage_unit_dim` VARCHAR( 7 ) NULL DEFAULT NULL ,
    ADD  `storage_secure` enum('No', 'Yes') DEFAULT 'No' ,
    ADD  `lot_description` VARCHAR( 100 ) NULL DEFAULT NULL , 
    ADD  `carport` TINYINT( 2 ) NULL DEFAULT NULL, 
    ADD  `parking_description` VARCHAR( 160 ) NULL DEFAULT NULL , 
    ADD  `fence` enum('Front Yard Fully Fenced', 'Property Fully Fenced', 'Backyard Full Fenced', 'Partial', 'None') DEFAULT 'None' ,
    ADD  `fence_type` VARCHAR( 60 ) NULL DEFAULT NULL , 
    ADD  `energy_description` VARCHAR( 72 ) NULL DEFAULT NULL ,
    ADD  `pool_length` TINYINT( 3 ) NULL DEFAULT NULL, 
    ADD  `pool_width` TINYINT( 3 ) NULL DEFAULT NULL, 
    ADD  `pool_description` VARCHAR( 52 ) NULL DEFAULT NULL , 
    ADD  `spa_description` VARCHAR( 35 ) NULL DEFAULT NULL , 
    ADD  `equestrian_description` VARCHAR( 37 ) NULL DEFAULT NULL , 
    ADD  `fall_spectacular` enum('No', 'Yes') DEFAULT 'No' ,
    
    ADD  `dishwasher_description` VARCHAR( 32 ) NULL DEFAULT NULL , 
    ADD  `disposal_included`  enum('No', 'Yes') DEFAULT 'No' ,
    ADD  `refrigerator_description` VARCHAR( 24 ) NULL DEFAULT NULL , 
    ADD  `dryer_included`  enum('No', 'Yes') DEFAULT 'No' ,
    ADD  `washer_dryer_location` VARCHAR( 43 ) NULL DEFAULT NULL , 
    ADD  `dryer_utilities` enum('None', 'Electric', 'LP Gas', 'Gas', 'Both') DEFAULT 'None' ,

    ADD  `fireplace_location` VARCHAR( 46 ) NULL DEFAULT NULL ,
    ADD  `court_approval`  enum('No', 'Yes') DEFAULT 'No' 
                ")->execute();

        $this->getDbConnection()->createCommand("
ALTER TABLE  `property_info_details_history` 
    ADD  `lot_sqft` INT( 11 ) NULL DEFAULT NULL ,
    ADD  `lot_depth` INT( 11 ) NULL DEFAULT NULL ,
    ADD  `lot_frontage` INT( 11 ) NULL DEFAULT NULL ,

    ADD  `subdivision_name_xp` VARCHAR( 30 ) NULL DEFAULT NULL ,
    ADD  `city` VARCHAR( 32 ) NULL DEFAULT NULL ,
    ADD  `town` VARCHAR( 32 ) NULL DEFAULT NULL ,
    ADD  `county` VARCHAR( 20 ) NULL DEFAULT NULL ,
    ADD  `subdivision_number` TINYINT( 4 ) NULL DEFAULT NULL ,
    ADD  `subdivision_num_search` TINYINT( 4 ) NULL DEFAULT NULL ,
    ADD  `metro_map_coor` VARCHAR( 2 ) NULL DEFAULT NULL ,
    ADD  `metro_map_page` TINYINT( 2 ) NULL DEFAULT NULL ,
    ADD  `metro_map_coor_xp` VARCHAR( 2 ) NULL DEFAULT NULL ,
    ADD  `metro_map_page_xp` TINYINT( 3 ) NULL DEFAULT NULL ,

    ADD  `add_liv_area` INT( 11 ) NULL DEFAULT NULL ,
    ADD  `total_liv_area` INT( 11 ) NULL DEFAULT NULL ,
    ADD  `mh_year_built` TINYINT( 4 ) NULL DEFAULT NULL ,
    ADD  `beds_total_poss` TINYINT( 2 ) NULL DEFAULT NULL ,
    ADD  `pool_indoor` enum('No', 'Yes') DEFAULT 'No' ,
    ADD  `spa_indoor`  enum('No', 'Yes') DEFAULT 'No' ,


    ADD  `model` VARCHAR( 10 ) NULL DEFAULT NULL ,
    ADD  `built_desc` VARCHAR( 18 ) NULL DEFAULT NULL ,
    ADD  `prop_desc` VARCHAR( 128 ) NULL DEFAULT NULL ,
    ADD  `parking_spaces` VARCHAR( 15 ) NULL DEFAULT NULL ,
    ADD  `carport_type` enum('', 'Attached Carport', 'Detached Carport') DEFAULT '' ,
    ADD  `converted_garage` enum('No', 'Yes') DEFAULT 'No' ,
    ADD  `studio` enum('No', 'Yes') DEFAULT 'No' ,
    ADD  `condo_conversion` enum('No', 'Yes') DEFAULT 'No' ,
    ADD  `unit_desc` VARCHAR( 128 ) NULL DEFAULT NULL ,


    ADD  `compass_point` enum('', 'South', 'North', 'West', 'East') DEFAULT '' ,
    ADD  `house_faces` enum('', 'South', 'North', 'West', 'East', 'M', 'G') DEFAULT '' ,
    ADD  `house_views` VARCHAR( 100 ) NULL DEFAULT NULL ,

    ADD  `jr_high_school` VARCHAR( 32 ) NULL DEFAULT NULL ,
    ADD  `high_school` VARCHAR( 36 ) NULL DEFAULT NULL ,
    ADD  `elementary_school` VARCHAR( 32 ) NULL DEFAULT NULL ,

    ADD  `association_features_available` VARCHAR( 320 ) NULL DEFAULT NULL ,
    ADD  `association_fee_1` INT( 11 ) NULL DEFAULT NULL ,
    ADD  `association_fee_1_type` enum('', 'Monthly', 'Quarterly', 'Yearly', 'None') DEFAULT '' ,
    ADD  `association_name` VARCHAR( 20 ) NULL DEFAULT NULL ,
    ADD  `association_fee_includes` VARCHAR( 132 ) NULL DEFAULT NULL ,
    ADD  `assessment` enum('No', 'Yes') DEFAULT 'No' ,
    ADD  `assessment_amount` INT( 11 ) NULL DEFAULT NULL ,
    ADD  `assessment_amount_type` enum('', 'Quarterly', 'Annually', 'Monthly') DEFAULT '' ,
    ADD  `sidlid` enum('No', 'Yes') DEFAULT 'No' ,
    ADD  `sidlid_annual_amount` INT( 11 ) NULL DEFAULT NULL ,
    ADD  `sidlid_balance` INT( 11 ) NULL DEFAULT NULL ,
    ADD  `association_fee_2` INT( 11 ) NULL DEFAULT NULL ,
    ADD  `association_fee_2_type` enum('', 'Monthly', 'Quarterly', 'Yearly', 'None') DEFAULT '' ,
    ADD  `master_plan_fee_amount`  INT( 11 ) NULL DEFAULT NULL ,
    ADD  `master_plan_fee_type` enum('', 'Monthly', 'Quarterly', 'Yearly', 'None') DEFAULT '' ,
    ADD  `security` VARCHAR( 60 ) NULL DEFAULT NULL ,
    ADD  `hoa_minimum_rental_cycle` enum('', '6 Months', '3 Months', 'Monthly', 'Annual', 'Other') DEFAULT '' ,
    ADD  `age_restricted_community` enum('No', 'Yes') DEFAULT 'No' ,
    ADD  `services_available_on_site` VARCHAR( 128 ) NULL DEFAULT NULL ,
    ADD  `on_site_staff` enum('No', 'Yes') DEFAULT 'No' ,
    ADD  `on_site_staff_includes` VARCHAR( 128 ) NULL DEFAULT NULL ,
    ADD  `association_phone` VARCHAR( 12 ) NULL DEFAULT NULL ,
    ADD  `restrictions` VARCHAR( 22 ) NULL DEFAULT NULL ,
    ADD  `prop_amenities_description` VARCHAR( 128 ) NULL DEFAULT NULL ,
    ADD  `maintenance` INT( 11 ) NULL DEFAULT NULL ,
    ADD  `management` INT( 11 ) NULL DEFAULT NULL ,

    ADD  `num_terraces` TINYINT( 2 ) NULL DEFAULT NULL ,
    ADD  `terrace_total_sqft` TINYINT( 5 ) NULL DEFAULT NULL ,
    ADD  `terrace_location` VARCHAR( 50 ) NULL DEFAULT NULL ,
    ADD  `storage_unit_desc` enum('', 'Association Owned', 'Leased', 'Owned') DEFAULT '' ,
    ADD  `storage_units_num` TINYINT( 2 ) NULL DEFAULT NULL ,
    ADD  `storage_unit_dim` VARCHAR( 7 ) NULL DEFAULT NULL ,
    ADD  `storage_secure` enum('No', 'Yes') DEFAULT 'No' ,
    ADD  `lot_description` VARCHAR( 100 ) NULL DEFAULT NULL , 
    ADD  `carport` TINYINT( 2 ) NULL DEFAULT NULL, 
    ADD  `parking_description` VARCHAR( 160 ) NULL DEFAULT NULL , 
    ADD  `fence` enum('Front Yard Fully Fenced', 'Property Fully Fenced', 'Backyard Full Fenced', 'Partial', 'None') DEFAULT 'None' ,
    ADD  `fence_type` VARCHAR( 60 ) NULL DEFAULT NULL , 
    ADD  `energy_description` VARCHAR( 72 ) NULL DEFAULT NULL ,
    ADD  `pool_length` TINYINT( 3 ) NULL DEFAULT NULL, 
    ADD  `pool_width` TINYINT( 3 ) NULL DEFAULT NULL, 
    ADD  `pool_description` VARCHAR( 52 ) NULL DEFAULT NULL , 
    ADD  `spa_description` VARCHAR( 35 ) NULL DEFAULT NULL , 
    ADD  `equestrian_description` VARCHAR( 37 ) NULL DEFAULT NULL , 
    ADD  `fall_spectacular` enum('No', 'Yes') DEFAULT 'No' ,
    
    ADD  `dishwasher_description` VARCHAR( 32 ) NULL DEFAULT NULL , 
    ADD  `disposal_included`  enum('No', 'Yes') DEFAULT 'No' ,
    ADD  `refrigerator_description` VARCHAR( 24 ) NULL DEFAULT NULL , 
    ADD  `dryer_included`  enum('No', 'Yes') DEFAULT 'No' ,
    ADD  `washer_dryer_location` VARCHAR( 43 ) NULL DEFAULT NULL , 
    ADD  `dryer_utilities` enum('None', 'Electric', 'LP Gas', 'Gas', 'Both') DEFAULT 'None' ,

    ADD  `fireplace_location` VARCHAR( 46 ) NULL DEFAULT NULL ,
    ADD  `court_approval`  enum('No', 'Yes') DEFAULT 'No' 

                ")->execute();
    }

    public function safeDown()
    {
        $this->getDbConnection()->createCommand("
ALTER TABLE `property_info_details`
    DROP `lot_sqft` ,
    DROP `lot_depth` ,
    DROP `lot_frontage` ,

    DROP `subdivision_name_xp` ,
    DROP `city` ,
    DROP `town` ,
    DROP `county` ,
    DROP `subdivision_number` ,
    DROP `subdivision_num_search` ,
    DROP `metro_map_coor` ,
    DROP `metro_map_page` ,
    DROP `metro_map_coor_xp` ,
    DROP `metro_map_page_xp` ,

    DROP `add_liv_area` ,
    DROP `total_liv_area` ,
    DROP `mh_year_built` ,
    DROP `beds_total_poss` ,
    DROP `pool_indoor` ,
    DROP `spa_indoor`  ,


    DROP `model` ,
    DROP `built_desc` ,
    DROP `prop_desc` ,
    DROP `parking_spaces` ,
    DROP `carport_type` ,
    DROP `converted_garage` ,
    DROP `studio` ,
    DROP `condo_conversion` ,
    DROP `unit_desc` ,


    DROP `compass_point` ,
    DROP `house_faces` ,
    DROP `house_views` ,

    DROP `jr_high_school` ,
    DROP `high_school` ,
    DROP `elementary_school` ,

    DROP `association_features_available` ,
    DROP `association_fee_1` ,
    DROP `association_fee_1_type` ,
    DROP `association_name` ,
    DROP `association_fee_includes` ,
    DROP `assessment` ,
    DROP `assessment_amount` ,
    DROP `assessment_amount_type` ,
    DROP `sidlid` ,
    DROP `sidlid_annual_amount` ,
    DROP `sidlid_balance` ,
    DROP `association_fee_2` ,
    DROP `association_fee_2_type` ,
    DROP `master_plan_fee_amount`  ,
    DROP `master_plan_fee_type` ,
    DROP `security` ,
    DROP `hoa_minimum_rental_cycle` ,
    DROP `age_restricted_community` ,
    DROP `services_available_on_site` ,
    DROP `on_site_staff` ,
    DROP `on_site_staff_includes` ,
    DROP `association_phone` ,
    DROP `restrictions` ,
    DROP `prop_amenities_description` ,
    DROP `maintenance` ,
    DROP `management` ,

    DROP  `num_terraces`  ,
    DROP  `terrace_total_sqft`  ,
    DROP  `terrace_location`  ,
    DROP  `storage_unit_desc`  ,
    DROP  `storage_units_num`  ,
    DROP  `storage_unit_dim`  ,
    DROP  `storage_secure`  ,
    DROP  `lot_description`  , 
    DROP  `carport` , 
    DROP  `parking_description`  , 
    DROP  `fence`  ,
    DROP  `fence_type` , 
    DROP  `energy_description` ,
    DROP  `pool_length` , 
    DROP  `pool_width` , 
    DROP  `pool_description`  , 
    DROP  `spa_description`  , 
    DROP  `equestrian_description`  , 
    DROP  `fall_spectacular` ,
    
    DROP  `dishwasher_description`  , 
    DROP  `disposal_included`   ,
    DROP  `refrigerator_description`  , 
    DROP  `dryer_included`  ,
    DROP  `washer_dryer_location`  , 
    DROP  `dryer_utilities` ,

    DROP  `fireplace_location` ,
    DROP  `court_approval`

    
                ")->execute();
        $this->getDbConnection()->createCommand("
ALTER TABLE `property_info_details_history`
    DROP `lot_sqft` ,
    DROP `lot_depth` ,
    DROP `lot_frontage` ,

    DROP `subdivision_name_xp` ,
    DROP `city` ,
    DROP `town` ,
    DROP `county` ,
    DROP `subdivision_number` ,
    DROP `subdivision_num_search` ,
    DROP `metro_map_coor` ,
    DROP `metro_map_page` ,
    DROP `metro_map_coor_xp` ,
    DROP `metro_map_page_xp` ,

    DROP `add_liv_area` ,
    DROP `total_liv_area` ,
    DROP `mh_year_built` ,
    DROP `beds_total_poss` ,
    DROP `pool_indoor` ,
    DROP `spa_indoor`  ,


    DROP `model` ,
    DROP `built_desc` ,
    DROP `prop_desc` ,
    DROP `parking_spaces` ,
    DROP `carport_type` ,
    DROP `converted_garage` ,
    DROP `studio` ,
    DROP `condo_conversion` ,
    DROP `unit_desc` ,


    DROP `compass_point` ,
    DROP `house_faces` ,
    DROP `house_views` ,

    DROP `jr_high_school` ,
    DROP `high_school` ,
    DROP `elementary_school` ,

    DROP `association_features_available` ,
    DROP `association_fee_1` ,
    DROP `association_fee_1_type` ,
    DROP `association_name` ,
    DROP `association_fee_includes` ,
    DROP `assessment` ,
    DROP `assessment_amount` ,
    DROP `assessment_amount_type` ,
    DROP `sidlid` ,
    DROP `sidlid_annual_amount` ,
    DROP `sidlid_balance` ,
    DROP `association_fee_2` ,
    DROP `association_fee_2_type` ,
    DROP `master_plan_fee_amount`  ,
    DROP `master_plan_fee_type` ,
    DROP `security` ,
    DROP `hoa_minimum_rental_cycle` ,
    DROP `age_restricted_community` ,
    DROP `services_available_on_site` ,
    DROP `on_site_staff` ,
    DROP `on_site_staff_includes` ,
    DROP `association_phone` ,
    DROP `restrictions` ,
    DROP `prop_amenities_description` ,
    DROP `maintenance` ,
    DROP `management`  ,

    DROP  `num_terraces`  ,
    DROP  `terrace_total_sqft`  ,
    DROP  `terrace_location`  ,
    DROP  `storage_unit_desc`  ,
    DROP  `storage_units_num`  ,
    DROP  `storage_unit_dim`  ,
    DROP  `storage_secure`  ,
    DROP  `lot_description`  , 
    DROP  `carport` , 
    DROP  `parking_description`  , 
    DROP  `fence`  ,
    DROP  `fence_type` , 
    DROP  `energy_description` ,
    DROP  `pool_length` , 
    DROP  `pool_width` , 
    DROP  `pool_description`  , 
    DROP  `spa_description`  , 
    DROP  `equestrian_description`  , 
    DROP  `fall_spectacular` ,
    
    DROP  `dishwasher_description`  , 
    DROP  `disposal_included`   ,
    DROP  `refrigerator_description`  , 
    DROP  `dryer_included`  ,
    DROP  `washer_dryer_location`  , 
    DROP  `dryer_utilities` ,

    DROP  `fireplace_location` ,
    DROP  `court_approval`
    
                ")->execute();
    }

}
