<?php

class m150407_091446_create_property_info_additional_brokerage_details extends CDbMigration
{
    public function up()
    {

        $this->createTable('{{property_info_additional_brokerage_details}}', [
            'property_info_brokerage_details' => 'integer',
            'property_id' => 'integer',
            'status' => 'string',
            'fireplace_features' => 'string',
            'heating_features' => 'string',
            'exterior_construction_features' => 'string',
            'roofing_features' => 'string',
            'interior_features' => 'string',
            'exterior_features' => 'string',
            'sales_history' => 'string',
            'tax_history' => 'string',
            'foreclosure' => 'string',
            'short_sale' => 'string',
            'page_link' => 'string',
            'updated_mid' => 'string',
            'brokerage_mid' => 'integer',
            'mls_id' => 'string',
            'pagent_name' => 'string',
            'pagent_phone' => 'string',
            'pagent_phone_fax' => 'string',
            'pagent_phone_home' => 'string',
            'pagent_phone_mobile' => 'string',
            'pagent_website' => 'string',
//            'list_agent_public_id' => 'integer',
//            'email' => 'string',
//            'buyer_broker_code' => 'string',
//            'buyer_agent_public_id' => 'integer',
//            'lo_phone' => 'string',
//            'list_office_code' => 'string',
//            'owner_licensee' => 'string',
//            'realtor' => 'string',
//            'sale_office_bonus' => 'string',
//            'commission_excluded' => 'string',
//            'commission_variable' => 'string',
//            'additional_showing' => 'string',
//            'ladom' => 'integer',
//            'home_protection_plan' => 'string',
//            'open_house_flag' => 'integer',
//            'list_date' => 'string',
//            'list_price' => 'integer',
//            'original_list_price' => 'integer',
//            'pricechgdate' => 'string',
//            'sale_price' => 'integer',
//            'previous_price' => 'integer',
//            'status_updates' => 'string',
//            't_status_date' => 'string',
//            'internet' => 'string',
//            'idx' => 'string',
//            'images' => 'integer',
//            'photo_excluded' => 'string',
//            'photo_instructions' => 'string',
//            'lpsqft_wcents' => 'string',
//            'lpsqft' => 'string',
//            'spsqft_wcents' => 'string',
//            'splp' => 'string',
//            'public_address' => 'string',
//            'commentary' => 'string',
//            'avm' => 'string',
//            'documentfolderid' => 'integer',
//            'documentfoldercount' => 'integer',
//            'record_delete_date' => 'string',
//            'record_delete_flag' => 'string',
//            'directions' => 'string',
//            'contingency_desc' => 'string',
//            'temp_off_mrkt_status_desc' => 'string',
//            'possession_description' => 'string',
//            'statuschangedate' => 'string',
//            'entry_date' => 'string',
//            'acceptance_date' => 'string',
//            'dom' => 'integer',
//            'active_dom' => 'integer',
//            'est_clolse_dt' => 'string',
//            'actual_close_date' => 'string',
//            'days_from_listing_to_close' => 'integer',
//            'last_transaction_code' => 'string',
//            'last_transaction_date' => 'string',
//            'package_available' => 'string',
//            'property_insurance' => 'integer',
//            'sold_appraisal' => 'integer',
//            'sold_down_payment' => 'integer',
//            'earnest_deposit' => 'integer',
//            'sellers_contribution' => 'integer',
//            'financing_considered' => 'string',
//            'amt_owner_will_carry' => 'integer',
//            'existing_rent' => 'integer',
//            'nod_date' => 'string',
//            'reporeo' => 'string',
//            'auction_date' => 'string',
//            'auction_type' => 'string',
//            'additional_au_sold_terms' => 'string',
//            'litigation' => 'string',
//            'litigation_type' => 'string',
//            'studio_rent' => 'integer',
//            'cap_rate' => 'string',
//            'gross_rent_multiplier' => 'string',
//            'owner_will_carry' => 'string',
//            'current_loan_assumable' => 'string',
//            'cash_to_assume' => 'integer',
//            'cost_per_unit' => 'integer',
//            'gross_operating_income' => 'integer',
//            'yearly_operating_income' => 'integer',
//            'tenant_pays' => 'string',
//            'other_income_description' => 'string',
//            'amount_owner_will_carry' => 'integer',
//            'noi' => 'integer',
//            'yearly_operating_expense' => 'integer',
//            'yearly_other_income' => 'integer',
//            'other_encumbrance_desc' => 'string',
//            'expense_source' => 'string',
//            'vacancy' => 'integer',
//            'service_contract_inc' => 'string',
//            'parcel_num' => 'string',
//            'legal_location_range' => 'integer',
//            'legal_lctn_range_search' => 'integer',
//            'legal_location_section' => 'integer',
//            'legal_lctn_section_search' => 'integer',
//            'legal_location_township' => 'integer',
//            'legal_lctntownship_search' => 'integer',
//            'tax_district' => 'string',
//            'assessed_imp_value' => 'integer',
//            'assessed_land_value' => 'integer',
//            'block_number' => 'string',
//            'lot_number' => 'string',
        ]);

    }


    public function down()
    {
        $this->dropTable('property_info_additional_brokerage_details');
    }
}