<?php

class m150407_091448_update_property_info_additional_brokerage_details extends CDbMigration
{
	// Use safeUp/safeDown to do migration with transaction
	public function safeUp()
	{
        $this->getDbConnection()->createCommand("
ALTER TABLE  `property_info_additional_brokerage_details` 
    ADD  `list_agent_public_id` INT( 11 ) NULL DEFAULT NULL, 
    ADD  `email` VARCHAR( 40 ) NULL DEFAULT NULL ,
    ADD  `buyer_broker_code` VARCHAR( 6 ) NULL DEFAULT NULL , 
    ADD  `buyer_agent_public_id` INT( 11 ) NULL DEFAULT NULL, 
    ADD  `lo_phone` VARCHAR( 12 ) NULL DEFAULT NULL , 
    ADD  `list_office_code` VARCHAR( 6 ) NULL DEFAULT NULL ,
    ADD  `owner_licensee` enum('No', 'Yes', 'Related') DEFAULT 'No', 
    ADD  `realtor` enum('No', 'Yes') DEFAULT 'No',
    ADD  `sale_office_bonus` enum('No', 'Yes') DEFAULT 'No', 
    ADD  `commission_excluded` enum('No', 'Yes') DEFAULT 'No', 
    ADD  `commission_variable` enum('No', 'Yes') DEFAULT 'No', 
    ADD  `additional_showing` VARCHAR( 55 ) NULL DEFAULT NULL ,
    ADD  `ladom` TINYINT( 5 ) NULL DEFAULT NULL, 
    ADD  `home_protection_plan` enum('No', 'Yes') DEFAULT 'No',

    ADD  `open_house_flag` TINYINT( 1 ) NULL DEFAULT NULL,

    ADD  `list_date` DATETIME NULL DEFAULT NULL, 
    ADD  `list_price` INT( 11 ) NULL DEFAULT NULL, 
    ADD  `original_list_price` INT( 11 ) NULL DEFAULT NULL, 
    ADD  `pricechgdate` DATETIME NULL DEFAULT NULL, 
    ADD  `sale_price` INT( 11 ) NULL DEFAULT NULL, 
    ADD  `previous_price` INT( 11 ) NULL DEFAULT NULL, 
    ADD  `status_updates` VARCHAR( 25 ) NULL DEFAULT NULL, 
    ADD  `t_status_date` DATETIME NULL DEFAULT NULL,  
    ADD  `internet` enum('No', 'Yes') DEFAULT 'No',
    ADD  `idx` VARCHAR( 1 ) NULL DEFAULT NULL, 
    ADD  `images` TINYINT( 2 ) NULL DEFAULT NULL, 
    ADD  `photo_excluded` enum('No', 'Yes') DEFAULT 'No', 
    ADD  `photo_instructions` enum('', 'User will upload by clicking on TOOLS in MLXchange/Fusion', 'No photo will be taken or supplied', 'MLSPHOT') DEFAULT '', 
    ADD  `last_image_trans_date` DATETIME NULL DEFAULT NULL,  
    ADD  `lpsqft_wcents` DECIMAL( 10, 2 ) NULL DEFAULT NULL, 
    ADD  `lpsqft` DECIMAL( 10, 2 ) NULL DEFAULT NULL, 
    ADD  `spsqft_wcents` DECIMAL( 10, 2 ) NULL DEFAULT NULL, 
    ADD  `splp` DECIMAL( 10, 2 ) NULL DEFAULT NULL, 
    ADD  `public_address` enum('No', 'Yes') DEFAULT 'No',
    ADD  `commentary` enum('No', 'Yes') DEFAULT 'No',
    ADD  `avm` enum('No', 'Yes') DEFAULT 'No',
    ADD  `documentfolderid` INT( 11 ) NULL DEFAULT NULL, 
    ADD  `documentfoldercount` TINYINT( 3 ) NULL DEFAULT NULL, 
    ADD  `record_delete_date` DATETIME NULL DEFAULT NULL,
    ADD  `record_delete_flag` enum('No', 'Yes') DEFAULT 'No', 
    ADD  `directions` VARCHAR( 170 ) NULL DEFAULT NULL ,

    ADD  `contingency_desc` enum('', 'Offer Accepted Pending Final Signatures', 'Short Sale Approval', 'Sell Buyer Property', 'Release of Liens', 'Court Approval', 'Inspections', 'Financing') DEFAULT '',  
    ADD  `temp_off_mrkt_status_desc` VARCHAR( 52 ) NULL DEFAULT NULL ,
    ADD  `possession_description` enum('', 'Estimated Completion Date', 'Current Lease Agreement', 'By Agreement-CLA', 'Close of Escrow', 'Immediate') DEFAULT '',
    ADD  `statuschangedate` DATETIME NULL DEFAULT NULL, 
    ADD  `entry_date` DATETIME NULL DEFAULT NULL, 
    ADD  `acceptance_date` DATETIME NULL DEFAULT NULL, 
    ADD  `dom` TINYINT( 4 ) NULL DEFAULT NULL, 
    ADD  `active_dom` TINYINT( 4 ) NULL DEFAULT NULL, 
    ADD  `est_clolse_dt` DATETIME NULL DEFAULT NULL, 
    ADD  `actual_close_date` DATETIME NULL DEFAULT NULL, 
    ADD  `days_from_listing_to_close` TINYINT( 4 ) NULL DEFAULT NULL,
    ADD  `last_transaction_code` VARCHAR( 2 ) NULL DEFAULT NULL ,
    ADD  `last_transaction_date` DATETIME NULL DEFAULT NULL, 
    ADD  `package_available` enum('No', 'Yes') DEFAULT 'No', 
    ADD  `property_insurance` INT( 11 ) NULL DEFAULT NULL, 
    ADD  `sold_appraisal` INT( 11 ) NULL DEFAULT NULL, 
    ADD  `sold_down_payment` INT( 11 ) NULL DEFAULT NULL, 
    
    ADD  `earnest_deposit` INT( 11 ) NULL DEFAULT NULL, 
    ADD  `sellers_contribution` INT( 11 ) NULL DEFAULT NULL, 
    ADD  `financing_considered`  VARCHAR( 84 ) NULL DEFAULT NULL ,
    ADD  `amt_owner_will_carry` INT( 11 ) NULL DEFAULT NULL, 
    ADD  `existing_rent` INT( 11 ) NULL DEFAULT NULL, 
    
    ADD  `nod_date` DATETIME NULL DEFAULT NULL, 
    ADD  `reporeo` enum('No', 'Yes') DEFAULT 'No', 
    ADD  `auction_date` DATETIME NULL DEFAULT NULL, 
    ADD  `auction_type` enum('', 'Absolute', 'Reserve') DEFAULT '',
    ADD  `additional_au_sold_terms` VARCHAR( 12 ) NULL DEFAULT NULL , 
    ADD  `litigation` enum('Unknown', 'No', 'Yes') DEFAULT 'Unknown', 
    ADD  `litigation_type` enum('', 'Construction Defect', 'Association', 'Both', 'Other') DEFAULT '',
    ADD  `studio_rent` TINYINT( 4 ) NULL DEFAULT NULL, 
    ADD  `cap_rate` DECIMAL( 10, 3 ) NULL DEFAULT NULL,
    ADD  `gross_rent_multiplier` DECIMAL( 10, 3 ) NULL DEFAULT NULL, 
    ADD  `owner_will_carry` enum('No', 'Yes') DEFAULT 'No',  
    ADD  `current_loan_assumable` enum('', 'No', 'Yes') DEFAULT '',  
    ADD  `cash_to_assume` INT( 11 ) NULL DEFAULT NULL, 
    ADD  `cost_per_unit` INT( 11 ) NULL DEFAULT NULL, 
    ADD  `gross_operating_income` INT( 11 ) NULL DEFAULT NULL, 
    ADD  `yearly_operating_income` INT( 11 ) NULL DEFAULT NULL, 
    ADD  `tenant_pays` VARCHAR( 50 ) NULL DEFAULT NULL , 
    ADD  `other_income_description` VARCHAR( 60 ) NULL DEFAULT NULL , 
    ADD  `amount_owner_will_carry`  INT( 11 ) NULL DEFAULT NULL, 
    ADD  `noi` INT( 11 ) NULL DEFAULT NULL, 
    ADD  `yearly_operating_expense` INT( 11 ) NULL DEFAULT NULL, 
    ADD  `yearly_other_income` INT( 11 ) NULL DEFAULT NULL, 
    ADD  `other_encumbrance_desc` VARCHAR( 16 ) NULL DEFAULT NULL , 
    ADD  `expense_source` VARCHAR( 60 ) NULL DEFAULT NULL , 
    ADD  `vacancy` TINYINT( 4 ) NULL DEFAULT NULL, 
    ADD  `service_contract_inc` VARCHAR( 30 ) NULL DEFAULT NULL , 
    
    ADD  `parcel_num` VARCHAR( 44 ) NULL DEFAULT NULL , 
    ADD  `legal_location_range` TINYINT( 4 ) NULL DEFAULT NULL, 
    ADD  `legal_lctn_range_search` TINYINT( 4 ) NULL DEFAULT NULL, 
    ADD  `legal_location_section` TINYINT( 4 ) NULL DEFAULT NULL, 
    ADD  `legal_lctn_section_search` TINYINT( 4 ) NULL DEFAULT NULL, 
    ADD  `legal_location_township` TINYINT( 4 ) NULL DEFAULT NULL, 
    ADD  `legal_lctntownship_search` TINYINT( 4 ) NULL DEFAULT NULL, 
    ADD  `tax_district` VARCHAR( 20 ) NULL DEFAULT NULL , 
    ADD  `assessed_imp_value` INT( 11 ) NULL DEFAULT NULL, 
    ADD  `assessed_land_value` INT( 11 ) NULL DEFAULT NULL,
    ADD  `block_number` VARCHAR( 6 ) NULL DEFAULT NULL, 
    ADD  `lot_number` VARCHAR( 6 ) NULL DEFAULT NULL
    
                  ")->execute();
	}

	public function safeDown()
	{
        $this->getDbConnection()->createCommand("
ALTER TABLE  `property_info_additional_brokerage_details` 
    DROP `list_agent_public_id` , 
    DROP `email` ,
    DROP `buyer_broker_code` , 
    DROP `buyer_agent_public_id` , 
    DROP `lo_phone` , 
    DROP `list_office_code` ,
    DROP `owner_licensee` , 
    DROP `realtor` ,
    DROP `sale_office_bonus` , 
    DROP `commission_excluded` , 
    DROP `commission_variable` , 
    DROP `additional_showing`  ,
    DROP `ladom` , 
    DROP `home_protection_plan` ,

    DROP `open_house_flag`,

    DROP `list_date` , 
    DROP `list_price` , 
    DROP `original_list_price` , 
    DROP `pricechgdate` , 
    DROP `sale_price` , 
    DROP `previous_price` , 
    DROP `status_updates` , 
    DROP `t_status_date` ,  
    DROP `internet` ,
    DROP `idx`, 
    DROP `images` , 
    DROP `photo_excluded` , 
    DROP `photo_instructions` ,
    DROP `last_image_trans_date` ,
    DROP `lpsqft_wcents` , 
    DROP `lpsqft` , 
    DROP `spsqft_wcents` , 
    DROP `splp` , 
    DROP `public_address` ,
    DROP `commentary` ,
    DROP `avm` ,
    DROP `documentfolderid` , 
    DROP `documentfoldercount` , 
    DROP `record_delete_date` ,
    DROP `record_delete_flag` , 
    DROP `directions` ,

    DROP `contingency_desc` ,  
    DROP `temp_off_mrkt_status_desc` ,
    DROP `possession_description` ,
    DROP `statuschangedate` , 
    DROP `entry_date` , 
    DROP `acceptance_date` , 
    DROP `dom` , 
    DROP `active_dom` , 
    DROP `est_clolse_dt` , 
    DROP `actual_close_date` , 
    DROP `days_from_listing_to_close` ,
    DROP `last_transaction_code` ,
    DROP `last_transaction_date` , 
    DROP `package_available` , 
    DROP `property_insurance` , 
    DROP `sold_appraisal` , 
    DROP `sold_down_payment` , 
    
    DROP `earnest_deposit` , 
    DROP `sellers_contribution` , 
    DROP `financing_considered` ,
    DROP `amt_owner_will_carry` , 
    DROP `existing_rent` , 
    
    DROP `nod_date` , 
    DROP `reporeo` , 
    DROP `auction_date` , 
    DROP `auction_type` ,
    DROP `additional_au_sold_terms` , 
    DROP `litigation` , 
    DROP `litigation_type` ,
    DROP `studio_rent` , 
    DROP `cap_rate` ,
    DROP `gross_rent_multiplier` , 
    DROP `owner_will_carry` ,  
    DROP `current_loan_assumable` ,  
    DROP `cash_to_assume` , 
    DROP `cost_per_unit` , 
    DROP `gross_operating_income` , 
    DROP `yearly_operating_income` , 
    DROP `tenant_pays` , 
    DROP `other_income_description`, 
    DROP `amount_owner_will_carry`  , 
    DROP `noi` , 
    DROP `yearly_operating_expense` , 
    DROP `yearly_other_income` , 
    DROP `other_encumbrance_desc` , 
    DROP `expense_source` , 
    DROP `vacancy` , 
    DROP `service_contract_inc` , 
    
    DROP `parcel_num` , 
    DROP `legal_location_range` , 
    DROP `legal_lctn_range_search` , 
    DROP `legal_location_section` , 
    DROP `legal_lctn_section_search` , 
    DROP `legal_location_township` , 
    DROP `legal_lctntownship_search` , 
    DROP `tax_district` , 
    DROP `assessed_imp_value` , 
    DROP `assessed_land_value` ,
    DROP `block_number`, 
    DROP `lot_number`
                  ")->execute();
	}

}